modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MerchantPug/BrewinAndChewin/issues"
license = "MIT License"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
# updateJSONURL=""
displayURL = "https://github.com/MerchantPug/BrewinAndChewin"
logoFile = "logo.png"
logoBlur = false
authors="${mod_authors}"
description="${mod_description}"
itemIcon="brewinandchewin:keg"
configBackground = "minecraft:textures/block/bricks.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "farmersdelight"
mandatory = true
versionRange = "${farmers_delight_version_range}"
ordering = "NONE"
side = "BOTH"